
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/test.sqlite3

test:
  <<: *default
  database: db/test.sqlite3
# staging:
#   <<: *default
#   database: db/test.sqlite3
# production:
# g  <<: *default
#   database: db/test.sqlite3

staging:
  adapter: mysql2
  database: new_dku_develop
  username: root
  password: ''
  encoding: utf8
  host: localhost
  timeout: 5000

production:
  adapter: mysql2
  database: new_dku
  username: Seunghyum
  password: justdoit12
  encoding: utf8mb4
  host: new-dku.ctjjwc8t09iy.ap-northeast-2.rds.amazonaws.com
  port: 3306
  timeout: 5000
