
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/test.sqlite3

# test:
#   <<: *default
#   database: db/test.sqlite3
# staging:
#   <<: *default
#   database: db/test.sqlite3
# production:
#   <<: *default
#   database: db/test.sqlite3

staging:
  adapter: mysql2
  database: dku
  username: Seunghyum
  password: '12341234'
  encoding: utf8
  host: new-dku.ctjjwc8t09iy.ap-northeast-2.rds.amazonaws.com
  port: 3306
  timeout: 5000
#
# production:
#   adapter: mysql2
#   username: Seunghyum
#   database: ebdb
#   password: justdoit12
#   encoding: utf8mb4
#   host: aag23zeaqbk00f.ctjjwc8t09iy.ap-northeast-2.rds.amazonaws.com
#   port: 3306
#   timeout: 5000
