# default:
#   toolbar:
#     - undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image codesample

#   plugins:
#     - link
#     - codesample
#     - uploadimage

#   height: 300

#   uploadimage_form_url: '/tinymce_s3_image_upload'
toolbar:
  - undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image codesample | table
  
plugins:
  - image
  - link